spring:
  config:
    import: ${CRYPTO_RESEARCH_MANAGED_SECRETS_LOCATION:file:./config/application-managed-secrets.properties}
  datasource:
    url: ${CRYPTO_RESEARCH_MANAGED_DB_URL}
    username: ${CRYPTO_RESEARCH_MANAGED_DB_USERNAME}
    password: ${CRYPTO_RESEARCH_MANAGED_DB_PASSWORD}
